#!/bin/sh

start() {
  if ! pgrep -f $1 ;
  then
    $@&
  fi 
}

# music
start mpd
start mpDris2 # add playerctl support to mpd

# compositor
start picom --experimental-backends --config $HOME/.config/awesome/configuration/picom.conf

# auth
start /usr/libexec/polkit-gnome-authentication-agent-1

# load X colors
start xrdb $HOME/.Xresources

# load fcitx5
start fcitx5 -d

# load clash
start /opt/clash-for-windows-bin/cfw
